//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TinySpline {

public class Domain : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Domain(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Domain obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Domain() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          tinysplinecsharpPINVOKE.delete_Domain(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Domain(double min, double max) : this(tinysplinecsharpPINVOKE.new_Domain__SWIG_0(min, max), true) {
    if (tinysplinecsharpPINVOKE.SWIGPendingException.Pending) throw tinysplinecsharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public Domain(Domain other) : this(tinysplinecsharpPINVOKE.new_Domain__SWIG_1(Domain.getCPtr(other)), true) {
    if (tinysplinecsharpPINVOKE.SWIGPendingException.Pending) throw tinysplinecsharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string ToString() {
    string ret = tinysplinecsharpPINVOKE.Domain_ToString(swigCPtr);
    if (tinysplinecsharpPINVOKE.SWIGPendingException.Pending) throw tinysplinecsharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Min {
    get {
      double ret = tinysplinecsharpPINVOKE.Domain_Min_get(swigCPtr);
      if (tinysplinecsharpPINVOKE.SWIGPendingException.Pending) throw tinysplinecsharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double Max {
    get {
      double ret = tinysplinecsharpPINVOKE.Domain_Max_get(swigCPtr);
      if (tinysplinecsharpPINVOKE.SWIGPendingException.Pending) throw tinysplinecsharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
