//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TinySpline {

class tinysplinecsharpPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="SWIGRegisterExceptionCallbacks_tinysplinecsharp")]
    public static extern void SWIGRegisterExceptionCallbacks_tinysplinecsharp(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_tinysplinecsharp")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_tinysplinecsharp(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_tinysplinecsharp(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_tinysplinecsharp(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="SWIGRegisterStringCallback_tinysplinecsharp")]
    public static extern void SWIGRegisterStringCallback_tinysplinecsharp(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_tinysplinecsharp(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static tinysplinecsharpPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_TS_MAX_NUM_KNOTS_get")]
  public static extern int TS_MAX_NUM_KNOTS_get();

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_TS_DOMAIN_DEFAULT_MIN_get")]
  public static extern double TS_DOMAIN_DEFAULT_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_TS_DOMAIN_DEFAULT_MAX_get")]
  public static extern double TS_DOMAIN_DEFAULT_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_TS_KNOT_EPSILON_get")]
  public static extern double TS_KNOT_EPSILON_get();

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_TS_CONTROL_POINT_EPSILON_get")]
  public static extern double TS_CONTROL_POINT_EPSILON_get();

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_degree")]
  public static extern uint ts_bspline_degree(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_set_degree")]
  public static extern int ts_bspline_set_degree(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_order")]
  public static extern uint ts_bspline_order(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_set_order")]
  public static extern int ts_bspline_set_order(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_dimension")]
  public static extern uint ts_bspline_dimension(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_set_dimension")]
  public static extern int ts_bspline_set_dimension(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_len_control_points")]
  public static extern uint ts_bspline_len_control_points(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_num_control_points")]
  public static extern uint ts_bspline_num_control_points(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_sof_control_points")]
  public static extern uint ts_bspline_sof_control_points(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_control_points")]
  public static extern int ts_bspline_control_points(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_control_point_at")]
  public static extern int ts_bspline_control_point_at(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_set_control_points")]
  public static extern int ts_bspline_set_control_points(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_set_control_point_at")]
  public static extern int ts_bspline_set_control_point_at(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_num_knots")]
  public static extern uint ts_bspline_num_knots(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_sof_knots")]
  public static extern uint ts_bspline_sof_knots(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_knots")]
  public static extern int ts_bspline_knots(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_knot_at")]
  public static extern int ts_bspline_knot_at(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_set_knots")]
  public static extern int ts_bspline_set_knots(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_set_knot_at")]
  public static extern int ts_bspline_set_knot_at(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, double jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_knot")]
  public static extern double ts_deboornet_knot(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_index")]
  public static extern uint ts_deboornet_index(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_multiplicity")]
  public static extern uint ts_deboornet_multiplicity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_num_insertions")]
  public static extern uint ts_deboornet_num_insertions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_dimension")]
  public static extern uint ts_deboornet_dimension(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_len_points")]
  public static extern uint ts_deboornet_len_points(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_num_points")]
  public static extern uint ts_deboornet_num_points(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_sof_points")]
  public static extern uint ts_deboornet_sof_points(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_points")]
  public static extern int ts_deboornet_points(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_len_result")]
  public static extern uint ts_deboornet_len_result(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_num_result")]
  public static extern uint ts_deboornet_num_result(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_sof_result")]
  public static extern uint ts_deboornet_sof_result(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_result")]
  public static extern int ts_deboornet_result(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_init")]
  public static extern global::System.IntPtr ts_bspline_init();

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_new")]
  public static extern int ts_bspline_new(uint jarg1, uint jarg2, uint jarg3, int jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_copy")]
  public static extern int ts_bspline_copy(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_move")]
  public static extern void ts_bspline_move(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_free")]
  public static extern void ts_bspline_free(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_init")]
  public static extern global::System.IntPtr ts_deboornet_init();

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_copy")]
  public static extern int ts_deboornet_copy(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_move")]
  public static extern void ts_deboornet_move(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_deboornet_free")]
  public static extern void ts_deboornet_free(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_interpolate_cubic_natural")]
  public static extern int ts_bspline_interpolate_cubic_natural(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_interpolate_catmull_rom")]
  public static extern int ts_bspline_interpolate_catmull_rom(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, double jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, double jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_eval")]
  public static extern int ts_bspline_eval(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_eval_all")]
  public static extern int ts_bspline_eval_all(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_sample")]
  public static extern int ts_bspline_sample(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_bisect")]
  public static extern int ts_bspline_bisect(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, int jarg4, uint jarg5, int jarg6, uint jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_domain")]
  public static extern void ts_bspline_domain(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_is_closed")]
  public static extern int ts_bspline_is_closed(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_derive")]
  public static extern int ts_bspline_derive(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, double jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_insert_knot")]
  public static extern int ts_bspline_insert_knot(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, uint jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_split")]
  public static extern int ts_bspline_split(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_tension")]
  public static extern int ts_bspline_tension(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_to_beziers")]
  public static extern int ts_bspline_to_beziers(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_to_json")]
  public static extern int ts_bspline_to_json(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_from_json")]
  public static extern int ts_bspline_from_json(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_save")]
  public static extern int ts_bspline_save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_bspline_load")]
  public static extern int ts_bspline_load(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_knots_equal")]
  public static extern int ts_knots_equal(double jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_arr_fill")]
  public static extern void ts_arr_fill(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_ts_distance")]
  public static extern double ts_distance(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_DeBoorNet")]
  public static extern global::System.IntPtr new_DeBoorNet(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_delete_DeBoorNet")]
  public static extern void delete_DeBoorNet(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_DeBoorNet_ToString")]
  public static extern string DeBoorNet_ToString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_DeBoorNet_Knot_get")]
  public static extern double DeBoorNet_Knot_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_DeBoorNet_Index_get")]
  public static extern uint DeBoorNet_Index_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_DeBoorNet_Multiplicity_get")]
  public static extern uint DeBoorNet_Multiplicity_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_DeBoorNet_NumInsertions_get")]
  public static extern uint DeBoorNet_NumInsertions_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_DeBoorNet_Dimension_get")]
  public static extern uint DeBoorNet_Dimension_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_DeBoorNet_Points_get")]
  public static extern global::System.IntPtr DeBoorNet_Points_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_DeBoorNet_Result_get")]
  public static extern global::System.IntPtr DeBoorNet_Result_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_Domain__SWIG_0")]
  public static extern global::System.IntPtr new_Domain__SWIG_0(double jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_Domain__SWIG_1")]
  public static extern global::System.IntPtr new_Domain__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_Domain_ToString")]
  public static extern string Domain_ToString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_Domain_Min_get")]
  public static extern double Domain_Min_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_Domain_Max_get")]
  public static extern double Domain_Max_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_delete_Domain")]
  public static extern void delete_Domain(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_BSpline__SWIG_0")]
  public static extern global::System.IntPtr new_BSpline__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_BSpline__SWIG_1")]
  public static extern global::System.IntPtr new_BSpline__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_BSpline__SWIG_2")]
  public static extern global::System.IntPtr new_BSpline__SWIG_2(uint jarg1, uint jarg2, uint jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_BSpline__SWIG_3")]
  public static extern global::System.IntPtr new_BSpline__SWIG_3(uint jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_BSpline__SWIG_4")]
  public static extern global::System.IntPtr new_BSpline__SWIG_4(uint jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_BSpline__SWIG_5")]
  public static extern global::System.IntPtr new_BSpline__SWIG_5(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_delete_BSpline")]
  public static extern void delete_BSpline(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_InterpolateCubicNatural")]
  public static extern global::System.IntPtr BSpline_InterpolateCubicNatural(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_InterpolateCatmullRom__SWIG_0")]
  public static extern global::System.IntPtr BSpline_InterpolateCatmullRom__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, double jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, double jarg6);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_InterpolateCatmullRom__SWIG_1")]
  public static extern global::System.IntPtr BSpline_InterpolateCatmullRom__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, double jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_InterpolateCatmullRom__SWIG_2")]
  public static extern global::System.IntPtr BSpline_InterpolateCatmullRom__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, double jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_InterpolateCatmullRom__SWIG_3")]
  public static extern global::System.IntPtr BSpline_InterpolateCatmullRom__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_InterpolateCatmullRom__SWIG_4")]
  public static extern global::System.IntPtr BSpline_InterpolateCatmullRom__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_FromJson")]
  public static extern global::System.IntPtr BSpline_FromJson(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Load")]
  public static extern global::System.IntPtr BSpline_Load(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_ControlPointAt")]
  public static extern global::System.IntPtr BSpline_ControlPointAt(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_KnotAt")]
  public static extern double BSpline_KnotAt(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Eval")]
  public static extern global::System.IntPtr BSpline_Eval(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_EvalAll")]
  public static extern global::System.IntPtr BSpline_EvalAll(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Sample__SWIG_0")]
  public static extern global::System.IntPtr BSpline_Sample__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Sample__SWIG_1")]
  public static extern global::System.IntPtr BSpline_Sample__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Bisect__SWIG_0")]
  public static extern global::System.IntPtr BSpline_Bisect__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, bool jarg4, uint jarg5, bool jarg6, uint jarg7);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Bisect__SWIG_1")]
  public static extern global::System.IntPtr BSpline_Bisect__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, bool jarg4, uint jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Bisect__SWIG_2")]
  public static extern global::System.IntPtr BSpline_Bisect__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, bool jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Bisect__SWIG_3")]
  public static extern global::System.IntPtr BSpline_Bisect__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Bisect__SWIG_4")]
  public static extern global::System.IntPtr BSpline_Bisect__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Bisect__SWIG_5")]
  public static extern global::System.IntPtr BSpline_Bisect__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_IsClosed__SWIG_0")]
  public static extern bool BSpline_IsClosed__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_IsClosed__SWIG_1")]
  public static extern bool BSpline_IsClosed__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_ToJson")]
  public static extern string BSpline_ToJson(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Save")]
  public static extern void BSpline_Save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_SetControlPointAt")]
  public static extern void BSpline_SetControlPointAt(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_SetKnotAt")]
  public static extern void BSpline_SetKnotAt(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_InsertKnot")]
  public static extern global::System.IntPtr BSpline_InsertKnot(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Split")]
  public static extern global::System.IntPtr BSpline_Split(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Tension")]
  public static extern global::System.IntPtr BSpline_Tension(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_ToBeziers")]
  public static extern global::System.IntPtr BSpline_ToBeziers(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Derive__SWIG_0")]
  public static extern global::System.IntPtr BSpline_Derive__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Derive__SWIG_1")]
  public static extern global::System.IntPtr BSpline_Derive__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Derive__SWIG_2")]
  public static extern global::System.IntPtr BSpline_Derive__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_ToString")]
  public static extern string BSpline_ToString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Degree_get")]
  public static extern uint BSpline_Degree_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Order_get")]
  public static extern uint BSpline_Order_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Dimension_get")]
  public static extern uint BSpline_Dimension_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_NumControlPoints_get")]
  public static extern uint BSpline_NumControlPoints_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Domain_get")]
  public static extern global::System.IntPtr BSpline_Domain_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_ControlPoints_set")]
  public static extern void BSpline_ControlPoints_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_ControlPoints_get")]
  public static extern global::System.IntPtr BSpline_ControlPoints_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Knots_set")]
  public static extern void BSpline_Knots_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_BSpline_Knots_get")]
  public static extern global::System.IntPtr BSpline_Knots_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_Utils_KnotsEqual")]
  public static extern bool Utils_KnotsEqual(double jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_delete_Utils")]
  public static extern void delete_Utils(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_Clear")]
  public static extern void RealVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_Add")]
  public static extern void RealVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_size")]
  public static extern uint RealVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_capacity")]
  public static extern uint RealVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_reserve")]
  public static extern void RealVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_Vector__SWIG_0")]
  public static extern global::System.IntPtr new_Vector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_Vector__SWIG_1")]
  public static extern global::System.IntPtr new_Vector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_new_Vector__SWIG_2")]
  public static extern global::System.IntPtr new_Vector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_getitemcopy")]
  public static extern double RealVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_getitem")]
  public static extern double RealVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_setitem")]
  public static extern void RealVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_AddRange")]
  public static extern void RealVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_GetRange")]
  public static extern global::System.IntPtr RealVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_Insert")]
  public static extern void RealVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_InsertRange")]
  public static extern void RealVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_RemoveAt")]
  public static extern void RealVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_RemoveRange")]
  public static extern void RealVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_Repeat")]
  public static extern global::System.IntPtr RealVector_Repeat(double jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_Reverse__SWIG_0")]
  public static extern void RealVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_Reverse__SWIG_1")]
  public static extern void RealVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_SetRange")]
  public static extern void RealVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_Contains")]
  public static extern bool RealVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_IndexOf")]
  public static extern int RealVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_LastIndexOf")]
  public static extern int RealVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_RealVector_Remove")]
  public static extern bool RealVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("tinysplinecsharp", EntryPoint="CSharp_TinySpline_delete_RealVector")]
  public static extern void delete_RealVector(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
